devices:
  - mac: "aa.bb.cc.dd.ee.12"
    ip: "124.145.14.47"
    name: "first"
  - mac: "aa.bb.cc.dd.ee.12"
    ip: "124.145.14.479"
    name: "second"
  - mac: "aa.bb.cc.dd.ee.12"
    ip: "124.145.14.47"
    name: "fedora"
lan_interface: "169.254.243.84"
mqtt_broker_url: "homeassistant.local"
port: 1883
mqtt_user: "usser"
mqtt_password: "password"
subscribe_topic: "home/rp/#"
wake_topic: "home/rp/wakeonlan"
command_topic: "home/rp/command"
